---
  - name: Check if the sources have already been downloaded
    stat: path={{ ezpublish_apache_vhost.root }}/ezpublish_legacy
    register: legacy_dir

  - name: Download eZ Publish sources
    #get_url: url=https://github.com/ezsystems/ezpublish-community/archive/{{ ezpublish_version }}.tar.gz
    # temporary fix
    get_url: url=http://share.ez.no/content/download/161941/957952/version/8/file/ezpublish5_community_project-2014.11.1-gpl-full.tar.gz
             dest=/tmp/ezpublish.tar.gz
    when: legacy_dir.stat.isdir is not defined or legacy_dir.stat.isdir != 1
    register: download_src

  - name: Create Apache root directory
    file: path={{ ezpublish_apache_vhost.root }} group={{ ezpublish_apache.group }} state=directory mode=0755

  - name: Untar eZ Publish sources
    command: tar zxf /tmp/ezpublish.tar.gz -C {{ ezpublish_apache_vhost.root }}  --strip-components 1
    when: download_src.changed
    notify: Restart Apache
